/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiResponseListDLCResponse
} from '../endpoints.schemas';





export const getGameDLCs = (
    gameId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseListDLCResponse>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/api/v1/games/${gameId}/dlcs`,options
    );
  }


export const getGetGameDLCsQueryKey = (gameId?: number,) => {
    return [`http://localhost:8080/api/v1/games/${gameId}/dlcs`] as const;
    }

    
export const getGetGameDLCsInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(gameId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameDLCsQueryKey(gameId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameDLCs>>> = ({ signal }) => getGameDLCs(gameId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(gameId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameDLCsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getGameDLCs>>>
export type GetGameDLCsInfiniteQueryError = AxiosError<unknown>


export function useGetGameDLCsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameDLCs>>,
          TError,
          Awaited<ReturnType<typeof getGameDLCs>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameDLCs>>,
          TError,
          Awaited<ReturnType<typeof getGameDLCs>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameDLCsInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameDLCsInfiniteQueryOptions(gameId,options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetGameDLCsQueryOptions = <TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameDLCsQueryKey(gameId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameDLCs>>> = ({ signal }) => getGameDLCs(gameId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(gameId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameDLCsQueryResult = NonNullable<Awaited<ReturnType<typeof getGameDLCs>>>
export type GetGameDLCsQueryError = AxiosError<unknown>


export function useGetGameDLCs<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameDLCs>>,
          TError,
          Awaited<ReturnType<typeof getGameDLCs>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCs<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGameDLCs>>,
          TError,
          Awaited<ReturnType<typeof getGameDLCs>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCs<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameDLCs<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameDLCsQueryOptions(gameId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetGameDLCsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(gameId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameDLCsQueryKey(gameId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameDLCs>>> = ({ signal }) => getGameDLCs(gameId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameDLCsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getGameDLCs>>>
export type GetGameDLCsSuspenseQueryError = AxiosError<unknown>


export function useGetGameDLCsSuspense<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCsSuspense<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCsSuspense<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameDLCsSuspense<TData = Awaited<ReturnType<typeof getGameDLCs>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameDLCsSuspenseQueryOptions(gameId,options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetGameDLCsSuspenseInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(gameId: number, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGameDLCsQueryKey(gameId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGameDLCs>>> = ({ signal }) => getGameDLCs(gameId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGameDLCsSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getGameDLCs>>>
export type GetGameDLCsSuspenseInfiniteQueryError = AxiosError<unknown>


export function useGetGameDLCsSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options: { query:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCsSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGameDLCsSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGameDLCsSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getGameDLCs>>>, TError = AxiosError<unknown>>(
 gameId: number, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof getGameDLCs>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGameDLCsSuspenseInfiniteQueryOptions(gameId,options)

  const query = useSuspenseInfiniteQuery(queryOptions , queryClient) as  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



