/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  SseEmitter
} from '../endpoints.schemas';





export const trackProgress = (
    progressId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SseEmitter>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/api/v1/uploads/${progressId}`,options
    );
  }


export const getTrackProgressQueryKey = (progressId?: string,) => {
    return [`http://localhost:8080/api/v1/uploads/${progressId}`] as const;
    }

    
export const getTrackProgressInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(progressId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackProgressQueryKey(progressId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackProgress>>> = ({ signal }) => trackProgress(progressId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(progressId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackProgressInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof trackProgress>>>
export type TrackProgressInfiniteQueryError = AxiosError<unknown>


export function useTrackProgressInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackProgress>>,
          TError,
          Awaited<ReturnType<typeof trackProgress>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgressInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackProgress>>,
          TError,
          Awaited<ReturnType<typeof trackProgress>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgressInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackProgressInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackProgressInfiniteQueryOptions(progressId,options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getTrackProgressQueryOptions = <TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(progressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackProgressQueryKey(progressId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackProgress>>> = ({ signal }) => trackProgress(progressId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(progressId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackProgressQueryResult = NonNullable<Awaited<ReturnType<typeof trackProgress>>>
export type TrackProgressQueryError = AxiosError<unknown>


export function useTrackProgress<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackProgress>>,
          TError,
          Awaited<ReturnType<typeof trackProgress>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgress<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackProgress>>,
          TError,
          Awaited<ReturnType<typeof trackProgress>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgress<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackProgress<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackProgressQueryOptions(progressId,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getTrackProgressSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(progressId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackProgressQueryKey(progressId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackProgress>>> = ({ signal }) => trackProgress(progressId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackProgressSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof trackProgress>>>
export type TrackProgressSuspenseQueryError = AxiosError<unknown>


export function useTrackProgressSuspense<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgressSuspense<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgressSuspense<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackProgressSuspense<TData = Awaited<ReturnType<typeof trackProgress>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackProgressSuspenseQueryOptions(progressId,options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getTrackProgressSuspenseInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(progressId: string, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackProgressQueryKey(progressId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackProgress>>> = ({ signal }) => trackProgress(progressId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackProgressSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof trackProgress>>>
export type TrackProgressSuspenseInfiniteQueryError = AxiosError<unknown>


export function useTrackProgressSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options: { query:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgressSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackProgressSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackProgressSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof trackProgress>>>, TError = AxiosError<unknown>>(
 progressId: string, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof trackProgress>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackProgressSuspenseInfiniteQueryOptions(progressId,options)

  const query = useSuspenseInfiniteQuery(queryOptions , queryClient) as  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



