/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useInfiniteQuery,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CsrfParams,
  CsrfToken
} from '../endpoints.schemas';





export const csrf = (
    params: CsrfParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CsrfToken>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/csrf`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getCsrfQueryKey = (params?: CsrfParams,) => {
    return [`http://localhost:8080/csrf`, ...(params ? [params]: [])] as const;
    }

    
export const getCsrfInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(params: CsrfParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCsrfQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof csrf>>> = ({ signal }) => csrf(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CsrfInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof csrf>>>
export type CsrfInfiniteQueryError = AxiosError<unknown>


export function useCsrfInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof csrf>>,
          TError,
          Awaited<ReturnType<typeof csrf>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrfInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof csrf>>,
          TError,
          Awaited<ReturnType<typeof csrf>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrfInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCsrfInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCsrfInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions , queryClient) as  UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getCsrfQueryOptions = <TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(params: CsrfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCsrfQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof csrf>>> = ({ signal }) => csrf(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CsrfQueryResult = NonNullable<Awaited<ReturnType<typeof csrf>>>
export type CsrfQueryError = AxiosError<unknown>


export function useCsrf<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof csrf>>,
          TError,
          Awaited<ReturnType<typeof csrf>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrf<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof csrf>>,
          TError,
          Awaited<ReturnType<typeof csrf>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrf<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCsrf<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCsrfQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getCsrfSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(params: CsrfParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCsrfQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof csrf>>> = ({ signal }) => csrf(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CsrfSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof csrf>>>
export type CsrfSuspenseQueryError = AxiosError<unknown>


export function useCsrfSuspense<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrfSuspense<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrfSuspense<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCsrfSuspense<TData = Awaited<ReturnType<typeof csrf>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCsrfSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getCsrfSuspenseInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(params: CsrfParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCsrfQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof csrf>>> = ({ signal }) => csrf(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CsrfSuspenseInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof csrf>>>
export type CsrfSuspenseInfiniteQueryError = AxiosError<unknown>


export function useCsrfSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options: { query:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrfSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCsrfSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCsrfSuspenseInfinite<TData = InfiniteData<Awaited<ReturnType<typeof csrf>>>, TError = AxiosError<unknown>>(
 params: CsrfParams, options?: { query?:Partial<UseSuspenseInfiniteQueryOptions<Awaited<ReturnType<typeof csrf>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCsrfSuspenseInfiniteQueryOptions(params,options)

  const query = useSuspenseInfiniteQuery(queryOptions , queryClient) as  UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



