/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiResponseVoid,
  GameMod,
  User
} from '../endpoints.schemas';





export const blockUserFromMod = (
    userId: User,
    modId: GameMod, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/v1/user/${userId}/blocks/mod/${modId}`,undefined,options
    );
  }



export const getBlockUserFromModMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromMod>>, TError,{userId: User;modId: GameMod}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof blockUserFromMod>>, TError,{userId: User;modId: GameMod}, TContext> => {

const mutationKey = ['blockUserFromMod'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blockUserFromMod>>, {userId: User;modId: GameMod}> = (props) => {
          const {userId,modId} = props ?? {};

          return  blockUserFromMod(userId,modId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BlockUserFromModMutationResult = NonNullable<Awaited<ReturnType<typeof blockUserFromMod>>>
    
    export type BlockUserFromModMutationError = AxiosError<unknown>

    export const useBlockUserFromMod = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromMod>>, TError,{userId: User;modId: GameMod}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blockUserFromMod>>,
        TError,
        {userId: User;modId: GameMod},
        TContext
      > => {

      const mutationOptions = getBlockUserFromModMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const unblockUserFromMod = (
    userId: User,
    modId: GameMod, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.delete(
      `http://localhost:8080/api/v1/user/${userId}/blocks/mod/${modId}`,options
    );
  }



export const getUnblockUserFromModMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromMod>>, TError,{userId: User;modId: GameMod}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromMod>>, TError,{userId: User;modId: GameMod}, TContext> => {

const mutationKey = ['unblockUserFromMod'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unblockUserFromMod>>, {userId: User;modId: GameMod}> = (props) => {
          const {userId,modId} = props ?? {};

          return  unblockUserFromMod(userId,modId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnblockUserFromModMutationResult = NonNullable<Awaited<ReturnType<typeof unblockUserFromMod>>>
    
    export type UnblockUserFromModMutationError = AxiosError<unknown>

    export const useUnblockUserFromMod = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromMod>>, TError,{userId: User;modId: GameMod}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unblockUserFromMod>>,
        TError,
        {userId: User;modId: GameMod},
        TContext
      > => {

      const mutationOptions = getUnblockUserFromModMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const blockUserFromInteraction = (
    userId: User, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/v1/user/${userId}/blocks/interaction`,undefined,options
    );
  }



export const getBlockUserFromInteractionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromInteraction>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof blockUserFromInteraction>>, TError,{userId: User}, TContext> => {

const mutationKey = ['blockUserFromInteraction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blockUserFromInteraction>>, {userId: User}> = (props) => {
          const {userId} = props ?? {};

          return  blockUserFromInteraction(userId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BlockUserFromInteractionMutationResult = NonNullable<Awaited<ReturnType<typeof blockUserFromInteraction>>>
    
    export type BlockUserFromInteractionMutationError = AxiosError<unknown>

    export const useBlockUserFromInteraction = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromInteraction>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blockUserFromInteraction>>,
        TError,
        {userId: User},
        TContext
      > => {

      const mutationOptions = getBlockUserFromInteractionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const unblockUserFromInteraction = (
    userId: User, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.delete(
      `http://localhost:8080/api/v1/user/${userId}/blocks/interaction`,options
    );
  }



export const getUnblockUserFromInteractionMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromInteraction>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromInteraction>>, TError,{userId: User}, TContext> => {

const mutationKey = ['unblockUserFromInteraction'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unblockUserFromInteraction>>, {userId: User}> = (props) => {
          const {userId} = props ?? {};

          return  unblockUserFromInteraction(userId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnblockUserFromInteractionMutationResult = NonNullable<Awaited<ReturnType<typeof unblockUserFromInteraction>>>
    
    export type UnblockUserFromInteractionMutationError = AxiosError<unknown>

    export const useUnblockUserFromInteraction = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromInteraction>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unblockUserFromInteraction>>,
        TError,
        {userId: User},
        TContext
      > => {

      const mutationOptions = getUnblockUserFromInteractionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const blockUserFromAuthorGlobally = (
    userId: User, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/v1/user/${userId}/blocks/global`,undefined,options
    );
  }



export const getBlockUserFromAuthorGloballyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromAuthorGlobally>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof blockUserFromAuthorGlobally>>, TError,{userId: User}, TContext> => {

const mutationKey = ['blockUserFromAuthorGlobally'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blockUserFromAuthorGlobally>>, {userId: User}> = (props) => {
          const {userId} = props ?? {};

          return  blockUserFromAuthorGlobally(userId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BlockUserFromAuthorGloballyMutationResult = NonNullable<Awaited<ReturnType<typeof blockUserFromAuthorGlobally>>>
    
    export type BlockUserFromAuthorGloballyMutationError = AxiosError<unknown>

    export const useBlockUserFromAuthorGlobally = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromAuthorGlobally>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blockUserFromAuthorGlobally>>,
        TError,
        {userId: User},
        TContext
      > => {

      const mutationOptions = getBlockUserFromAuthorGloballyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const unblockUserFromAuthorGlobally = (
    userId: User, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.delete(
      `http://localhost:8080/api/v1/user/${userId}/blocks/global`,options
    );
  }



export const getUnblockUserFromAuthorGloballyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromAuthorGlobally>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromAuthorGlobally>>, TError,{userId: User}, TContext> => {

const mutationKey = ['unblockUserFromAuthorGlobally'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unblockUserFromAuthorGlobally>>, {userId: User}> = (props) => {
          const {userId} = props ?? {};

          return  unblockUserFromAuthorGlobally(userId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnblockUserFromAuthorGloballyMutationResult = NonNullable<Awaited<ReturnType<typeof unblockUserFromAuthorGlobally>>>
    
    export type UnblockUserFromAuthorGloballyMutationError = AxiosError<unknown>

    export const useUnblockUserFromAuthorGlobally = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromAuthorGlobally>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unblockUserFromAuthorGlobally>>,
        TError,
        {userId: User},
        TContext
      > => {

      const mutationOptions = getUnblockUserFromAuthorGloballyMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const blockUserFromDM = (
    userId: User, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/v1/user/${userId}/blocks/dm`,undefined,options
    );
  }



export const getBlockUserFromDMMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromDM>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof blockUserFromDM>>, TError,{userId: User}, TContext> => {

const mutationKey = ['blockUserFromDM'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof blockUserFromDM>>, {userId: User}> = (props) => {
          const {userId} = props ?? {};

          return  blockUserFromDM(userId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BlockUserFromDMMutationResult = NonNullable<Awaited<ReturnType<typeof blockUserFromDM>>>
    
    export type BlockUserFromDMMutationError = AxiosError<unknown>

    export const useBlockUserFromDM = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof blockUserFromDM>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof blockUserFromDM>>,
        TError,
        {userId: User},
        TContext
      > => {

      const mutationOptions = getBlockUserFromDMMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const unblockUserFromDirectMessages = (
    userId: User, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.delete(
      `http://localhost:8080/api/v1/user/${userId}/blocks/dm`,options
    );
  }



export const getUnblockUserFromDirectMessagesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromDirectMessages>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromDirectMessages>>, TError,{userId: User}, TContext> => {

const mutationKey = ['unblockUserFromDirectMessages'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unblockUserFromDirectMessages>>, {userId: User}> = (props) => {
          const {userId} = props ?? {};

          return  unblockUserFromDirectMessages(userId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnblockUserFromDirectMessagesMutationResult = NonNullable<Awaited<ReturnType<typeof unblockUserFromDirectMessages>>>
    
    export type UnblockUserFromDirectMessagesMutationError = AxiosError<unknown>

    export const useUnblockUserFromDirectMessages = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unblockUserFromDirectMessages>>, TError,{userId: User}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unblockUserFromDirectMessages>>,
        TError,
        {userId: User},
        TContext
      > => {

      const mutationOptions = getUnblockUserFromDirectMessagesMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    