/**
 * Generated by orval v7.11.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiResponseVoid
} from '../endpoints.schemas';





export const createPresetCategories = (
    gameId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseVoid>> => {
    
    
    return axios.default.post(
      `http://localhost:8080/api/v1/games/categories/${gameId}/create-preset-categories`,undefined,options
    );
  }



export const getCreatePresetCategoriesMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresetCategories>>, TError,{gameId: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createPresetCategories>>, TError,{gameId: number}, TContext> => {

const mutationKey = ['createPresetCategories'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPresetCategories>>, {gameId: number}> = (props) => {
          const {gameId} = props ?? {};

          return  createPresetCategories(gameId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreatePresetCategoriesMutationResult = NonNullable<Awaited<ReturnType<typeof createPresetCategories>>>
    
    export type CreatePresetCategoriesMutationError = AxiosError<unknown>

    export const useCreatePresetCategories = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPresetCategories>>, TError,{gameId: number}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPresetCategories>>,
        TError,
        {gameId: number},
        TContext
      > => {

      const mutationOptions = getCreatePresetCategoriesMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    